apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-driver-cloudhub-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-driver-cloudhub-sc